---
name: Auto Update HumHub

on:
  repository_dispatch:
    types: check-update
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Execute Update
        id: update
        run: |
          . ./update.sh
          { echo "CUR_VERSION=$CUR_VERSION"; echo "NEW_VERSION=$NEW_VERSION"; echo "GIT_BRANCH=$GIT_BRANCH"; } >> "$GITHUB_ENV"
      - name: Check git status and log
        run: |
          git status
          git log
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "${{ env.GIT_BRANCH }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          title: "Bump HumHub to ${{ env.NEW_VERSION }}"
          body: "See Release notes at https://github.com/humhub/humhub/releases/tag/v${{ env.NEW_VERSION }}"
